### ISSUE TITLE
load empty string

### ISSUE THREAD

**Issue by PaulXiCao** [jannisteunissen/config_fortran#9] opened 2018-11-05 14:56 UTC
There seems to be no option to load an empty string. 
Something like
```
str = ""
```
will actually give you a string consisting of those two double quote signs.

**Comment by jannisteunissen** [comment] 2018-11-05 16:40
I'd expect to see that in the output of the m_config module, but if you use this string in your program, isn't the result an 'empty' string? (In Fortran, an empty string is padded with blanks/spaces)

**Comment by PaulXiCao** [comment] 2018-11-06 11:11
**Test 1**: just leave the value blank
```
str =
```
results in an error message: 
```
The following error occured in m_config:
  Cannot read line                      <num>  from <file>
```
where `<num>, <file>` refer to the line number and file name of the config file.

**Test 2**: As before with double quotes
```
str = ""
```
gives you a character variable consisting of two chars. Thus, if you print that variable it will display those two double quotes in contrast to displaying nothing for an empty string.

**Comment by jannisteunissen** [comment] 2018-11-06 17:56
I can reproduce your test 1 error. Assignment of an empty value leads to an error message (which makes sense for all variables types except perhaps strings).

However, if you assign "" to a string the result should simply be a blank string. That's what I get on my system, so I can't reproduce test 2. If you say 'print that variable', do you mean print the variable directly from Fortran or looking at the output of the config module?

**Comment by jannisteunissen** [comment] 2018-11-12 17:54
I've updated the module so that you can now specify empty string, for example on the command line. They are still printed as '' in the output of the module (to make clear that it is an empty string). Does this fix your problem?

**Comment by jannisteunissen** [comment] 2019-03-15 10:10
Assuming it is fixed, I'll close this issue now

**Closed as completed by jannisteunissen** 2019-03-15 10:10 UTC
